title: Kaushik Naidu
logo: /headshots/IMG_6530-photoaidcom-cropped.PNG
description: Email: kn423@cornell.edu
Location: Ithaca, NY
LinkedIn: Kaushik Naidu
Phone: +1 (607) 319-9958
show_downloads: true
theme: jekyll-theme-minimal
